const ERROR_CODES = Object.freeze({
    VALIDATION_ERROR: "VALIDATION_ERROR",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    NOT_FOUND: "NOT_FOUND",
    CONFLICT: "CONFLICT",
    INVALID_EMAIL: "INVALID_EMAIL",
    UNVERIFIED_EMAIL: "UNVERIFIED_EMAIL",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    TOKEN_INVALID: "TOKEN_INVALID",
    REFRESH_REVOKED: "REFRESH_REVOKED",
    VENUE_CONFLICT: "VENUE_CONFLICT",
    EVENT_FULL: "EVENT_FULL",
    REGISTRATION_CLOSED: "REGISTRATION_CLOSED",
    REGISTRATION_NOT_OPEN: "REGISTRATION_NOT_OPEN",
    DUPLICATE_REGISTRATION: "DUPLICATE_REGISTRATION",
    INVALID_STATE: "INVALID_STATE",
    CLUB_NOT_ACTIVE: "CLUB_NOT_ACTIVE"
});

module.exports = ERROR_CODES;
