const ERROR_CODES = Object.freeze({
    VALIDATION_ERROR: "VALIDATION_ERROR",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    NOT_FOUND: "NOT_FOUND",
    CONFLICT: "CONFLICT",
    INVALID_EMAIL: "INVALID_EMAIL",
    UNVERIFIED_EMAIL: "UNVERIFIED_EMAIL",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    TOKEN_INVALID: "TOKEN_INVALID",
    OTP_INVALID: "OTP_INVALID",
    OTP_EXPIRED: "OTP_EXPIRED",
    REFRESH_REVOKED: "REFRESH_REVOKED",
    VENUE_CONFLICT: "VENUE_CONFLICT",
    EVENT_FULL: "EVENT_FULL",
    REGISTRATION_CLOSED: "REGISTRATION_CLOSED",
    REGISTRATION_NOT_OPEN: "REGISTRATION_NOT_OPEN",
    DUPLICATE_REGISTRATION: "DUPLICATE_REGISTRATION",
    NOT_ELIGIBLE: "NOT_ELIGIBLE",
    INVALID_STATE: "INVALID_STATE",
    CLUB_NOT_ACTIVE: "CLUB_NOT_ACTIVE",
    UPLOAD_ERROR: "UPLOAD_ERROR",
    RATE_LIMITED: "RATE_LIMITED",
    PHONE_REQUIRED: "PHONE_REQUIRED",
    // Registering for an event at the same time as one the student already holds a place for.
    SCHEDULE_CONFLICT: "SCHEDULE_CONFLICT"
});

module.exports = ERROR_CODES;
