const CLUB_REQUEST_STATUS = Object.freeze({
    PENDING_FACULTY_REVIEW: "PENDING_FACULTY_REVIEW",
    NEEDS_CHANGES: "NEEDS_CHANGES",
    FACULTY_VERIFIED: "FACULTY_VERIFIED",
    REJECTED: "REJECTED",
    APPROVED: "APPROVED"
});

const CLUB_STATUS = Object.freeze({
    APPROVED: "APPROVED",
    ACTIVE: "ACTIVE",
    SUSPENDED: "SUSPENDED",
    ARCHIVED: "ARCHIVED"
});

const MEMBERSHIP_STATUS = Object.freeze({
    PENDING: "PENDING",
    APPROVED: "APPROVED",
    REJECTED: "REJECTED"
});

const EVENT_STATUS = Object.freeze({
    DRAFT: "DRAFT",
    PENDING_APPROVAL: "PENDING_APPROVAL",
    NEEDS_CHANGES: "NEEDS_CHANGES",
    APPROVED: "APPROVED",
    PUBLISHED: "PUBLISHED",
    REJECTED: "REJECTED",
    CANCELLED: "CANCELLED",
    COMPLETED: "COMPLETED"
});

const REGISTRATION_STATUS = Object.freeze({
    REGISTERED: "REGISTERED",
    // In the queue for a full event; promoted to REGISTERED in order when a seat frees up.
    WAITLISTED: "WAITLISTED",
    CANCELLED: "CANCELLED"
});

// Proposed changes to a published event, reviewed by the faculty mentor before the club publishes them.
const REVISION_STATUS = Object.freeze({
    PENDING_APPROVAL: "PENDING_APPROVAL",
    NEEDS_CHANGES: "NEEDS_CHANGES",
    APPROVED: "APPROVED",
    REJECTED: "REJECTED"
});

const PARTICIPATION_MODES = Object.freeze({
    INDIVIDUAL: "INDIVIDUAL",
    TEAM: "TEAM"
});

// A team's roster entries: the leader who registered, and the students they invited.
const TEAM_MEMBER_STATUS = Object.freeze({
    LEADER: "LEADER",
    INVITED: "INVITED",
    ACCEPTED: "ACCEPTED",
    DECLINED: "DECLINED",
    CANCELLED: "CANCELLED",
    LEFT: "LEFT",
    REMOVED: "REMOVED"
});

const TEAM_STATUS = Object.freeze({
    ACTIVE: "ACTIVE",
    DISBANDED: "DISBANDED"
});

// Check-in at the door: the president opens it, officers scan tickets, and it closes when the event completes.
const CHECK_IN_STATUS = Object.freeze({
    NOT_STARTED: "NOT_STARTED",
    OPEN: "OPEN",
    CLOSED: "CLOSED"
});

const CHECK_IN_METHODS = Object.freeze({
    QR: "QR",
    MANUAL: "MANUAL"
});

// Recruitment drives: built by the president, approved by the faculty mentor, then published for applications.
const RECRUITMENT_STATUS = Object.freeze({
    DRAFT: "DRAFT",
    PENDING_APPROVAL: "PENDING_APPROVAL",
    NEEDS_CHANGES: "NEEDS_CHANGES",
    APPROVED: "APPROVED",
    REJECTED: "REJECTED",
    PUBLISHED: "PUBLISHED",
    COMPLETED: "COMPLETED",
    CANCELLED: "CANCELLED"
});

// One application per student per role. Selected students get an OFFER and accept at most one; the others
// close automatically. RESERVE candidates can be offered a seat that is declined or expires.
const APPLICATION_STATUS = Object.freeze({
    APPLIED: "APPLIED",
    IN_ROUNDS: "IN_ROUNDS",
    ELIMINATED: "ELIMINATED",
    OFFERED: "OFFERED",
    RESERVE: "RESERVE",
    ACCEPTED: "ACCEPTED",
    DECLINED: "DECLINED",
    EXPIRED: "EXPIRED",
    NOT_SELECTED: "NOT_SELECTED",
    WITHDRAWN: "WITHDRAWN"
});

const ROUND_STATUS = Object.freeze({
    DRAFT: "DRAFT",
    SCHEDULED: "SCHEDULED",
    RESULTS_PUBLISHED: "RESULTS_PUBLISHED"
});

// SCREENING: reviewed on paper, no meeting. ONLINE: meeting link. OFFLINE: venue on campus.
const ROUND_MODES = Object.freeze({ SCREENING: "SCREENING", ONLINE: "ONLINE", OFFLINE: "OFFLINE" });

// COMMON: everyone at the same time. SLOTS: one time slot per candidate.
const ROUND_TIMING = Object.freeze({ COMMON: "COMMON", SLOTS: "SLOTS" });

const ROUND_OUTCOMES = Object.freeze({ QUALIFIED: "QUALIFIED", ELIMINATED: "ELIMINATED" });

const QUESTION_TYPES = Object.freeze({
    SHORT: "SHORT",
    PARAGRAPH: "PARAGRAPH",
    SINGLE_CHOICE: "SINGLE_CHOICE",
    MULTI_CHOICE: "MULTI_CHOICE",
    LINK: "LINK",
    FILE: "FILE"
});

// Event gallery photos and videos: waiting for the president or vice-president, or public on the event.
const GALLERY_STATUS = Object.freeze({
    PENDING: "PENDING",
    APPROVED: "APPROVED"
});

const RESULT_STATUS = Object.freeze({
    DRAFT: "DRAFT",
    PUBLISHED: "PUBLISHED"
});

const VENUE_STATUS = Object.freeze({
    ACTIVE: "ACTIVE",
    INACTIVE: "INACTIVE"
});

const FEED_POST_TYPES = Object.freeze({
    EVENT: "EVENT",
    ANNOUNCEMENT: "ANNOUNCEMENT",
    EVENT_UPDATE: "EVENT_UPDATE",
    RESULT: "RESULT",
    CLUB_UPDATE: "CLUB_UPDATE"
});

const FEED_VISIBILITY = Object.freeze({
    PUBLIC: "PUBLIC",
    MEMBERS: "MEMBERS"
});

const NOTIFICATION_TYPES = Object.freeze({
    CLUB_REQUEST_UPDATE: "CLUB_REQUEST_UPDATE",
    CLUB_UPDATE: "CLUB_UPDATE",
    MEMBERSHIP_REQUEST: "MEMBERSHIP_REQUEST",
    MEMBERSHIP_APPROVED: "MEMBERSHIP_APPROVED",
    MEMBERSHIP_REJECTED: "MEMBERSHIP_REJECTED",
    CLUB_ROLE_CHANGED: "CLUB_ROLE_CHANGED",
    EVENT_REVIEW: "EVENT_REVIEW",
    EVENT_APPROVED: "EVENT_APPROVED",
    EVENT_CHANGES_REQUESTED: "EVENT_CHANGES_REQUESTED",
    EVENT_REJECTED: "EVENT_REJECTED",
    EVENT_PUBLISHED: "EVENT_PUBLISHED",
    EVENT_UPDATED: "EVENT_UPDATED",
    EVENT_CANCELLED: "EVENT_CANCELLED",
    REGISTRATION_CONFIRMED: "REGISTRATION_CONFIRMED",
    WAITLISTED: "WAITLISTED",
    REGISTRATION_REMOVED: "REGISTRATION_REMOVED",
    RESULT_PUBLISHED: "RESULT_PUBLISHED",
    ROUND_RESULTS: "ROUND_RESULTS",
    ANNOUNCEMENT: "ANNOUNCEMENT",
    NEW_CLUB: "NEW_CLUB",
    EVENT_CHANGES_REVIEW: "EVENT_CHANGES_REVIEW",
    TEAM_INVITE: "TEAM_INVITE",
    TEAM_UPDATE: "TEAM_UPDATE",
    CHECK_IN_OPEN: "CHECK_IN_OPEN",
    ATTENDANCE_MARKED: "ATTENDANCE_MARKED",
    GALLERY_SUBMITTED: "GALLERY_SUBMITTED",
    GALLERY_APPROVED: "GALLERY_APPROVED",
    GALLERY_REJECTED: "GALLERY_REJECTED",
    RECRUITMENT_REVIEW: "RECRUITMENT_REVIEW",
    RECRUITMENT_UPDATE: "RECRUITMENT_UPDATE",
    RECRUITMENT_OPEN: "RECRUITMENT_OPEN",
    APPLICATION_UPDATE: "APPLICATION_UPDATE",
    INTERVIEW_SCHEDULED: "INTERVIEW_SCHEDULED",
    INTERVIEW_REMINDER: "INTERVIEW_REMINDER",
    RECRUITMENT_OFFER: "RECRUITMENT_OFFER"
});

const AUDIT_ACTIONS = Object.freeze({
    USER_REGISTERED: "USER_REGISTERED",
    USER_STATUS_CHANGED: "USER_STATUS_CHANGED",
    PASSWORD_RESET: "PASSWORD_RESET",
    CLUB_REQUEST_SUBMITTED: "CLUB_REQUEST_SUBMITTED",
    CLUB_REQUEST_RESUBMITTED: "CLUB_REQUEST_RESUBMITTED",
    CLUB_REQUEST_VERIFIED: "CLUB_REQUEST_VERIFIED",
    CLUB_REQUEST_CHANGES_REQUESTED: "CLUB_REQUEST_CHANGES_REQUESTED",
    CLUB_REQUEST_REJECTED: "CLUB_REQUEST_REJECTED",
    CLUB_REQUEST_APPROVED: "CLUB_REQUEST_APPROVED",
    MENTOR_ASSIGNED: "MENTOR_ASSIGNED",
    PRESIDENT_ASSIGNED: "PRESIDENT_ASSIGNED",
    CLUB_UPDATED: "CLUB_UPDATED",
    CLUB_STATUS_CHANGED: "CLUB_STATUS_CHANGED",
    MEMBERSHIP_REQUESTED: "MEMBERSHIP_REQUESTED",
    MEMBERSHIP_APPROVED: "MEMBERSHIP_APPROVED",
    MEMBERSHIP_REJECTED: "MEMBERSHIP_REJECTED",
    MEMBER_ROLE_CHANGED: "MEMBER_ROLE_CHANGED",
    MEMBER_REMOVED: "MEMBER_REMOVED",
    MEMBER_LEFT: "MEMBER_LEFT",
    EVENT_CREATED: "EVENT_CREATED",
    EVENT_UPDATED: "EVENT_UPDATED",
    EVENT_SUBMITTED: "EVENT_SUBMITTED",
    EVENT_APPROVED: "EVENT_APPROVED",
    EVENT_CHANGES_REQUESTED: "EVENT_CHANGES_REQUESTED",
    EVENT_REJECTED: "EVENT_REJECTED",
    EVENT_PUBLISHED: "EVENT_PUBLISHED",
    EVENT_CANCELLED: "EVENT_CANCELLED",
    EVENT_COMPLETED: "EVENT_COMPLETED",
    STUDENT_REGISTERED: "STUDENT_REGISTERED",
    REGISTRATION_CANCELLED: "REGISTRATION_CANCELLED",
    PARTICIPANT_REMOVED: "PARTICIPANT_REMOVED",
    WAITLIST_JOINED: "WAITLIST_JOINED",
    WAITLIST_LEFT: "WAITLIST_LEFT",
    WAITLIST_PROMOTED: "WAITLIST_PROMOTED",
    RESULT_SAVED: "RESULT_SAVED",
    RESULT_PUBLISHED: "RESULT_PUBLISHED",
    RESULT_CORRECTED: "RESULT_CORRECTED",
    RESULT_ROUND_SAVED: "RESULT_ROUND_SAVED",
    RESULT_ROUND_DELETED: "RESULT_ROUND_DELETED",
    RESULT_ROUND_PUBLISHED: "RESULT_ROUND_PUBLISHED",
    RESULT_ROUND_UNPUBLISHED: "RESULT_ROUND_UNPUBLISHED",
    FEED_POST_CREATED: "FEED_POST_CREATED",
    FEED_POST_DELETED: "FEED_POST_DELETED",
    EVENT_REVISION_SUBMITTED: "EVENT_REVISION_SUBMITTED",
    EVENT_REVISION_APPROVED: "EVENT_REVISION_APPROVED",
    EVENT_REVISION_CHANGES_REQUESTED: "EVENT_REVISION_CHANGES_REQUESTED",
    EVENT_REVISION_REJECTED: "EVENT_REVISION_REJECTED",
    EVENT_REVISION_PUBLISHED: "EVENT_REVISION_PUBLISHED",
    EVENT_REVISION_DISCARDED: "EVENT_REVISION_DISCARDED",
    TEAM_CREATED: "TEAM_CREATED",
    TEAM_INVITE_SENT: "TEAM_INVITE_SENT",
    TEAM_INVITE_ACCEPTED: "TEAM_INVITE_ACCEPTED",
    TEAM_INVITE_DECLINED: "TEAM_INVITE_DECLINED",
    TEAM_MEMBER_LEFT: "TEAM_MEMBER_LEFT",
    TEAM_MEMBER_REMOVED: "TEAM_MEMBER_REMOVED",
    TEAM_DISBANDED: "TEAM_DISBANDED",
    TICKET_ISSUED: "TICKET_ISSUED",
    CHECK_IN_OPENED: "CHECK_IN_OPENED",
    CHECK_IN_CLOSED: "CHECK_IN_CLOSED",
    ATTENDANCE_MARKED: "ATTENDANCE_MARKED",
    ATTENDANCE_UNMARKED: "ATTENDANCE_UNMARKED",
    STORY_POSTED: "STORY_POSTED",
    STORY_DELETED: "STORY_DELETED",
    GALLERY_MEDIA_ADDED: "GALLERY_MEDIA_ADDED",
    GALLERY_MEDIA_APPROVED: "GALLERY_MEDIA_APPROVED",
    GALLERY_MEDIA_REJECTED: "GALLERY_MEDIA_REJECTED",
    GALLERY_MEDIA_REMOVED: "GALLERY_MEDIA_REMOVED",
    RECRUITMENT_CREATED: "RECRUITMENT_CREATED",
    RECRUITMENT_UPDATED: "RECRUITMENT_UPDATED",
    RECRUITMENT_SUBMITTED: "RECRUITMENT_SUBMITTED",
    RECRUITMENT_APPROVED: "RECRUITMENT_APPROVED",
    RECRUITMENT_CHANGES_REQUESTED: "RECRUITMENT_CHANGES_REQUESTED",
    RECRUITMENT_REJECTED: "RECRUITMENT_REJECTED",
    RECRUITMENT_PUBLISHED: "RECRUITMENT_PUBLISHED",
    RECRUITMENT_CLOSED: "RECRUITMENT_CLOSED",
    RECRUITMENT_EXTENDED: "RECRUITMENT_EXTENDED",
    RECRUITMENT_CANCELLED: "RECRUITMENT_CANCELLED",
    RECRUITMENT_COMPLETED: "RECRUITMENT_COMPLETED",
    APPLICATION_SUBMITTED: "APPLICATION_SUBMITTED",
    APPLICATION_UPDATED: "APPLICATION_UPDATED",
    APPLICATION_WITHDRAWN: "APPLICATION_WITHDRAWN",
    ROUND_CREATED: "ROUND_CREATED",
    ROUND_SCHEDULED: "ROUND_SCHEDULED",
    ROUND_RESULTS_PUBLISHED: "ROUND_RESULTS_PUBLISHED",
    INTERVIEW_SLOT_CHANGED: "INTERVIEW_SLOT_CHANGED",
    OFFER_MADE: "OFFER_MADE",
    OFFER_ACCEPTED: "OFFER_ACCEPTED",
    OFFER_DECLINED: "OFFER_DECLINED",
    OFFER_EXPIRED: "OFFER_EXPIRED",
    POSITION_FINALIZED: "POSITION_FINALIZED",
    CLUB_ROLE_CREATED: "CLUB_ROLE_CREATED",
    CLUB_ROLE_UPDATED: "CLUB_ROLE_UPDATED",
    CLUB_ROLE_DELETED: "CLUB_ROLE_DELETED",
    PRESIDENCY_TRANSFERRED: "PRESIDENCY_TRANSFERRED"
});

// Only events that have cleared faculty review hold a venue slot; drafts and
// pending events are checked against these at create, submit, approve and publish time.
// A submitted event reserves its venue while it waits for the mentor, so two clubs cannot request the same slot.
// Drafts and events sent back for changes do not hold a venue.
const EVENT_STATUSES_HOLDING_VENUE = [EVENT_STATUS.PENDING_APPROVAL, EVENT_STATUS.APPROVED, EVENT_STATUS.PUBLISHED];

const PUBLIC_EVENT_STATUSES = [EVENT_STATUS.PUBLISHED, EVENT_STATUS.COMPLETED];

const EDITABLE_EVENT_STATUSES = [EVENT_STATUS.DRAFT, EVENT_STATUS.NEEDS_CHANGES];

module.exports = {
    CLUB_REQUEST_STATUS,
    CLUB_STATUS,
    MEMBERSHIP_STATUS,
    EVENT_STATUS,
    REGISTRATION_STATUS,
    RESULT_STATUS,
    REVISION_STATUS,
    PARTICIPATION_MODES,
    TEAM_MEMBER_STATUS,
    TEAM_STATUS,
    CHECK_IN_STATUS,
    CHECK_IN_METHODS,
    GALLERY_STATUS,
    RECRUITMENT_STATUS,
    APPLICATION_STATUS,
    ROUND_STATUS,
    ROUND_MODES,
    ROUND_TIMING,
    ROUND_OUTCOMES,
    QUESTION_TYPES,
    VENUE_STATUS,
    FEED_POST_TYPES,
    FEED_VISIBILITY,
    NOTIFICATION_TYPES,
    AUDIT_ACTIONS,
    EVENT_STATUSES_HOLDING_VENUE,
    PUBLIC_EVENT_STATUSES,
    EDITABLE_EVENT_STATUSES
};
