const CLUB_REQUEST_STATUS = Object.freeze({
    PENDING_COORDINATOR_REVIEW: "PENDING_COORDINATOR_REVIEW",
    COORDINATOR_RECOMMENDED: "COORDINATOR_RECOMMENDED",
    PENDING_ADMIN_APPROVAL: "PENDING_ADMIN_APPROVAL",
    REJECTED: "REJECTED",
    APPROVED: "APPROVED"
});

const CLUB_STATUS = Object.freeze({
    PENDING: "PENDING",
    APPROVED: "APPROVED",
    ACTIVE: "ACTIVE",
    SUSPENDED: "SUSPENDED",
    ARCHIVED: "ARCHIVED"
});

const MEMBERSHIP_STATUS = Object.freeze({
    PENDING: "PENDING",
    APPROVED: "APPROVED",
    REJECTED: "REJECTED"
});

const EVENT_STATUS = Object.freeze({
    DRAFT: "DRAFT",
    PENDING_APPROVAL: "PENDING_APPROVAL",
    APPROVED: "APPROVED",
    PUBLISHED: "PUBLISHED",
    REJECTED: "REJECTED",
    CANCELLED: "CANCELLED",
    COMPLETED: "COMPLETED"
});

const REGISTRATION_STATUS = Object.freeze({
    REGISTERED: "REGISTERED",
    CANCELLED: "CANCELLED"
});

const RESULT_STATUS = Object.freeze({
    DRAFT: "DRAFT",
    PUBLISHED: "PUBLISHED"
});

const VENUE_STATUS = Object.freeze({
    ACTIVE: "ACTIVE",
    INACTIVE: "INACTIVE"
});

const AUDIT_ACTIONS = Object.freeze({
    CLUB_REQUEST_SUBMITTED: "CLUB_REQUEST_SUBMITTED",
    CLUB_REQUEST_RECOMMENDED: "CLUB_REQUEST_RECOMMENDED",
    CLUB_REQUEST_REJECTED: "CLUB_REQUEST_REJECTED",
    CLUB_REQUEST_APPROVED: "CLUB_REQUEST_APPROVED",
    COORDINATOR_ASSIGNED: "COORDINATOR_ASSIGNED",
    COORDINATOR_UNASSIGNED: "COORDINATOR_UNASSIGNED",
    PRESIDENT_ASSIGNED: "PRESIDENT_ASSIGNED",
    CLUB_STATUS_CHANGED: "CLUB_STATUS_CHANGED",
    EVENT_SUBMITTED: "EVENT_SUBMITTED",
    EVENT_APPROVED: "EVENT_APPROVED",
    EVENT_REJECTED: "EVENT_REJECTED",
    EVENT_PUBLISHED: "EVENT_PUBLISHED",
    EVENT_CANCELLED: "EVENT_CANCELLED",
    EVENT_COMPLETED: "EVENT_COMPLETED",
    RESULT_PUBLISHED: "RESULT_PUBLISHED"
});

const EVENT_STATUSES_HOLDING_VENUE = [
    EVENT_STATUS.DRAFT,
    EVENT_STATUS.PENDING_APPROVAL,
    EVENT_STATUS.APPROVED,
    EVENT_STATUS.PUBLISHED
];

const PUBLIC_EVENT_STATUSES = [
    EVENT_STATUS.PUBLISHED,
    EVENT_STATUS.COMPLETED
];

module.exports = {
    CLUB_REQUEST_STATUS,
    CLUB_STATUS,
    MEMBERSHIP_STATUS,
    EVENT_STATUS,
    REGISTRATION_STATUS,
    RESULT_STATUS,
    VENUE_STATUS,
    AUDIT_ACTIONS,
    EVENT_STATUSES_HOLDING_VENUE,
    PUBLIC_EVENT_STATUSES
};
