const CLUB_REQUEST_STATUS = Object.freeze({
    PENDING_FACULTY_REVIEW: "PENDING_FACULTY_REVIEW",
    NEEDS_CHANGES: "NEEDS_CHANGES",
    FACULTY_VERIFIED: "FACULTY_VERIFIED",
    REJECTED: "REJECTED",
    APPROVED: "APPROVED"
});

const CLUB_STATUS = Object.freeze({
    APPROVED: "APPROVED",
    ACTIVE: "ACTIVE",
    SUSPENDED: "SUSPENDED",
    ARCHIVED: "ARCHIVED"
});

const MEMBERSHIP_STATUS = Object.freeze({
    PENDING: "PENDING",
    APPROVED: "APPROVED",
    REJECTED: "REJECTED"
});

const EVENT_STATUS = Object.freeze({
    DRAFT: "DRAFT",
    PENDING_APPROVAL: "PENDING_APPROVAL",
    NEEDS_CHANGES: "NEEDS_CHANGES",
    APPROVED: "APPROVED",
    PUBLISHED: "PUBLISHED",
    REJECTED: "REJECTED",
    CANCELLED: "CANCELLED",
    COMPLETED: "COMPLETED"
});

const REGISTRATION_STATUS = Object.freeze({
    REGISTERED: "REGISTERED",
    // In the queue for a full event; promoted to REGISTERED in order when a seat frees up.
    WAITLISTED: "WAITLISTED",
    CANCELLED: "CANCELLED"
});

const RESULT_STATUS = Object.freeze({
    DRAFT: "DRAFT",
    PUBLISHED: "PUBLISHED"
});

const VENUE_STATUS = Object.freeze({
    ACTIVE: "ACTIVE",
    INACTIVE: "INACTIVE"
});

const FEED_POST_TYPES = Object.freeze({
    EVENT: "EVENT",
    ANNOUNCEMENT: "ANNOUNCEMENT",
    EVENT_UPDATE: "EVENT_UPDATE",
    RESULT: "RESULT",
    CLUB_UPDATE: "CLUB_UPDATE"
});

const FEED_VISIBILITY = Object.freeze({
    PUBLIC: "PUBLIC",
    MEMBERS: "MEMBERS"
});

const NOTIFICATION_TYPES = Object.freeze({
    CLUB_REQUEST_UPDATE: "CLUB_REQUEST_UPDATE",
    CLUB_UPDATE: "CLUB_UPDATE",
    MEMBERSHIP_REQUEST: "MEMBERSHIP_REQUEST",
    MEMBERSHIP_APPROVED: "MEMBERSHIP_APPROVED",
    MEMBERSHIP_REJECTED: "MEMBERSHIP_REJECTED",
    CLUB_ROLE_CHANGED: "CLUB_ROLE_CHANGED",
    EVENT_REVIEW: "EVENT_REVIEW",
    EVENT_APPROVED: "EVENT_APPROVED",
    EVENT_CHANGES_REQUESTED: "EVENT_CHANGES_REQUESTED",
    EVENT_REJECTED: "EVENT_REJECTED",
    EVENT_PUBLISHED: "EVENT_PUBLISHED",
    EVENT_UPDATED: "EVENT_UPDATED",
    EVENT_CANCELLED: "EVENT_CANCELLED",
    REGISTRATION_CONFIRMED: "REGISTRATION_CONFIRMED",
    WAITLISTED: "WAITLISTED",
    REGISTRATION_REMOVED: "REGISTRATION_REMOVED",
    RESULT_PUBLISHED: "RESULT_PUBLISHED",
    ROUND_RESULTS: "ROUND_RESULTS",
    ANNOUNCEMENT: "ANNOUNCEMENT",
    NEW_CLUB: "NEW_CLUB"
});

const AUDIT_ACTIONS = Object.freeze({
    USER_REGISTERED: "USER_REGISTERED",
    USER_STATUS_CHANGED: "USER_STATUS_CHANGED",
    PASSWORD_RESET: "PASSWORD_RESET",
    CLUB_REQUEST_SUBMITTED: "CLUB_REQUEST_SUBMITTED",
    CLUB_REQUEST_RESUBMITTED: "CLUB_REQUEST_RESUBMITTED",
    CLUB_REQUEST_VERIFIED: "CLUB_REQUEST_VERIFIED",
    CLUB_REQUEST_CHANGES_REQUESTED: "CLUB_REQUEST_CHANGES_REQUESTED",
    CLUB_REQUEST_REJECTED: "CLUB_REQUEST_REJECTED",
    CLUB_REQUEST_APPROVED: "CLUB_REQUEST_APPROVED",
    MENTOR_ASSIGNED: "MENTOR_ASSIGNED",
    PRESIDENT_ASSIGNED: "PRESIDENT_ASSIGNED",
    CLUB_UPDATED: "CLUB_UPDATED",
    CLUB_STATUS_CHANGED: "CLUB_STATUS_CHANGED",
    MEMBERSHIP_REQUESTED: "MEMBERSHIP_REQUESTED",
    MEMBERSHIP_APPROVED: "MEMBERSHIP_APPROVED",
    MEMBERSHIP_REJECTED: "MEMBERSHIP_REJECTED",
    MEMBER_ROLE_CHANGED: "MEMBER_ROLE_CHANGED",
    MEMBER_REMOVED: "MEMBER_REMOVED",
    MEMBER_LEFT: "MEMBER_LEFT",
    EVENT_CREATED: "EVENT_CREATED",
    EVENT_UPDATED: "EVENT_UPDATED",
    EVENT_SUBMITTED: "EVENT_SUBMITTED",
    EVENT_APPROVED: "EVENT_APPROVED",
    EVENT_CHANGES_REQUESTED: "EVENT_CHANGES_REQUESTED",
    EVENT_REJECTED: "EVENT_REJECTED",
    EVENT_PUBLISHED: "EVENT_PUBLISHED",
    EVENT_CANCELLED: "EVENT_CANCELLED",
    EVENT_COMPLETED: "EVENT_COMPLETED",
    STUDENT_REGISTERED: "STUDENT_REGISTERED",
    REGISTRATION_CANCELLED: "REGISTRATION_CANCELLED",
    PARTICIPANT_REMOVED: "PARTICIPANT_REMOVED",
    WAITLIST_JOINED: "WAITLIST_JOINED",
    WAITLIST_LEFT: "WAITLIST_LEFT",
    WAITLIST_PROMOTED: "WAITLIST_PROMOTED",
    RESULT_SAVED: "RESULT_SAVED",
    RESULT_PUBLISHED: "RESULT_PUBLISHED",
    RESULT_CORRECTED: "RESULT_CORRECTED",
    RESULT_ROUND_SAVED: "RESULT_ROUND_SAVED",
    RESULT_ROUND_DELETED: "RESULT_ROUND_DELETED",
    RESULT_ROUND_PUBLISHED: "RESULT_ROUND_PUBLISHED",
    RESULT_ROUND_UNPUBLISHED: "RESULT_ROUND_UNPUBLISHED",
    FEED_POST_CREATED: "FEED_POST_CREATED",
    FEED_POST_DELETED: "FEED_POST_DELETED",
    STORY_POSTED: "STORY_POSTED",
    STORY_DELETED: "STORY_DELETED"
});

// Only events that have cleared faculty review hold a venue slot; drafts and
// pending events are checked against these at create, submit, approve and publish time.
// A submitted event reserves its venue while it waits for the mentor, so two clubs cannot request the same slot.
// Drafts and events sent back for changes do not hold a venue.
const EVENT_STATUSES_HOLDING_VENUE = [EVENT_STATUS.PENDING_APPROVAL, EVENT_STATUS.APPROVED, EVENT_STATUS.PUBLISHED];

const PUBLIC_EVENT_STATUSES = [EVENT_STATUS.PUBLISHED, EVENT_STATUS.COMPLETED];

const EDITABLE_EVENT_STATUSES = [EVENT_STATUS.DRAFT, EVENT_STATUS.NEEDS_CHANGES];

module.exports = {
    CLUB_REQUEST_STATUS,
    CLUB_STATUS,
    MEMBERSHIP_STATUS,
    EVENT_STATUS,
    REGISTRATION_STATUS,
    RESULT_STATUS,
    VENUE_STATUS,
    FEED_POST_TYPES,
    FEED_VISIBILITY,
    NOTIFICATION_TYPES,
    AUDIT_ACTIONS,
    EVENT_STATUSES_HOLDING_VENUE,
    PUBLIC_EVENT_STATUSES,
    EDITABLE_EVENT_STATUSES
};
